# Generated by Django 4.2.28 on 2026-02-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_course_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('STUDENT', 'Students'), ('TEACHER', 'Teachers')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Dennis Osadebay University', max_length=160)),
                ('short_name', models.CharField(default='DOU', max_length=40)),
                ('official_website', models.URLField(blank=True, default='')),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=220)),
                ('current_session', models.CharField(default='2026/2027', max_length=20)),
                ('current_semester', models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester'), ('SUMMER', 'Summer Semester')], default='FIRST', max_length=10)),
                ('allow_student_signup', models.BooleanField(default=True)),
                ('allow_teacher_signup', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution Settings',
                'verbose_name_plural': 'Institution Settings',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='academic_session',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('JUPEB', 'JUPEB'), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('600', '600 Level'), ('PG', 'Postgraduate')], default='100', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester'), ('SUMMER', 'Summer Semester')], default='FIRST', max_length=10),
        ),
    ]
