# Generated by Django 4.2.28 on 2026-03-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enable_proctoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='shuffle_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='tab_switches',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
