# Generated by Codex on 2026-03-23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_student_current_level_student_department_and_more"),
        ("exam", "0009_course_enable_proctoring_course_shuffle_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="allow_navigation",
            field=models.BooleanField(default=True, help_text="Allow students to go back to previous questions"),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="exam.category"),
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="show_explanation_after_exam",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="course",
            name="shuffle_options",
            field=models.BooleanField(default=True),
        ),
        migrations.RenameField(
            model_name="question",
            old_name="question",
            new_name="question_text",
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="questions/"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.CharField(help_text="Correct option number (e.g. 1) or text for Short Answer", max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="option1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
                ("current_question_index", models.PositiveIntegerField(default=0)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam.course")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="student.student")),
            ],
            options={
                "unique_together": {("student", "course", "is_completed")},
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("selected_option", models.CharField(blank=True, max_length=500, null=True)),
                ("is_correct", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam.question")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="exam.examsession")),
            ],
        ),
        migrations.AddField(
            model_name="result",
            name="suspicious_activity_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
