# Generated by Django 4.2.28 on 2025-02-06 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('GRADUATE_ASSISTANT', 'Graduate Assistant'), ('ASSISTANT_LECTURER', 'Assistant Lecturer'), ('LECTURER_II', 'Lecturer II'), ('LECTURER_I', 'Lecturer I'), ('SENIOR_LECTURER', 'Senior Lecturer'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('PROFESSOR', 'Professor'), ('ADJUNCT', 'Adjunct Lecturer')], default='LECTURER_II', max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='faculty',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='staff_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Nigerian phone number (e.g. 08031234567 or +2348031234567).', regex='^(\\+234|0)[789][01]\\d{8}$')]),
        ),
    ]
