# Generated by Codex on 2026-03-23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student", "0003_student_current_level_student_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("GRADUATED", "Graduated"),
                    ("SUSPENDED", "Suspended"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="student_profile", to=settings.AUTH_USER_MODEL),
        ),
    ]
