# Generated by Django 4.2.28 on 2026-02-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_current_level_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_level',
            field=models.CharField(choices=[('JUPEB', 'JUPEB'), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('600', '600 Level'), ('PG', 'Postgraduate')], default='100', max_length=10),
        ),
    ]
